services:
  open-telemetry-collector:
    restart: unless-stopped
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./open_telemetry/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888
    networks:
      drybox:
        ipv4_address: 10.5.0.5

networks:
  drybox:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
