services:
  open-telemetry-collector:
    restart: unless-stopped
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./open_telemetry/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 8888:8888
    env_file:
      - ./.env
    networks:
      drybox:
        ipv4_address: 10.5.0.5
  environment-monitor:
    restart: unless-stopped
    privileged: true
    build:
      context: ./environment_monitor
    depends_on:
      - open-telemetry-collector
    env_file:
      - ./.env
    devices:
      - /dev/gpiomem:/dev/gpiomem
    networks:
      drybox:
        ipv4_address: 10.5.0.6

networks:
  drybox:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
